const docx = require('docx');
const fs = require('fs');

// Create a minimal BESS quote template for debugging
const doc = new docx.Document({
  sections: [
    {
      properties: {},
      children: [
        // Simple title
        new docx.Paragraph({
          children: [
            new docx.TextRun({
              text: "BATTERY ENERGY STORAGE SYSTEM QUOTE",
              bold: true,
              size: 32,
              color: "1E40AF"
            })
          ],
          alignment: docx.AlignmentType.CENTER,
          spacing: { after: 400 }
        }),

        // Basic project info
        new docx.Paragraph({
          children: [
            new docx.TextRun({
              text: "Project: {PROJECT_NAME}",
              bold: true,
              size: 24
            })
          ],
          spacing: { after: 200 }
        }),

        new docx.Paragraph({
          children: [
            new docx.TextRun({
              text: "Client: {CLIENT_NAME}",
              size: 22
            })
          ],
          spacing: { after: 200 }
        }),

        new docx.Paragraph({
          children: [
            new docx.TextRun({
              text: "Date: {QUOTE_DATE}",
              size: 22
            })
          ],
          spacing: { after: 400 }
        }),

        // Financial summary
        new docx.Paragraph({
          children: [
            new docx.TextRun({
              text: "FINANCIAL SUMMARY",
              bold: true,
              size: 28,
              color: "1E40AF"
            })
          ],
          spacing: { after: 200 }
        }),

        new docx.Paragraph({
          children: [
            new docx.TextRun({
              text: "Total Investment: {GRAND_CAPEX}",
              bold: true,
              size: 22,
              color: "059669"
            })
          ],
          spacing: { after: 200 }
        }),

        new docx.Paragraph({
          children: [
            new docx.TextRun({
              text: "Annual Savings: {ANNUAL_SAVINGS}",
              bold: true,
              size: 22,
              color: "059669"
            })
          ],
          spacing: { after: 200 }
        }),

        new docx.Paragraph({
          children: [
            new docx.TextRun({
              text: "Payback Period: {ROI_YEARS} years",
              bold: true,
              size: 22,
              color: "7C3AED"
            })
          ],
          spacing: { after: 400 }
        }),

        // Footer
        new docx.Paragraph({
          children: [
            new docx.TextRun({
              text: "Generated by Merlin BESS Quote Builder",
              italics: true,
              size: 20,
              color: "666666"
            })
          ],
          alignment: docx.AlignmentType.CENTER
        })
      ]
    }
  ]
});

// Generate and save the document
docx.Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync('./server/templates/BESS_Quote_Template_Minimal.docx', buffer);
  console.log('Created minimal template: BESS_Quote_Template_Minimal.docx');
  console.log('Features:');
  console.log('- Minimal structure for debugging');
  console.log('- No tables or complex formatting');
  console.log('- Basic text and placeholders only');
});