version: "2"

build:
  builder: "dockerfile"

deploy:
  startCommand: "npm start"
  healthcheckPath: "/api/health"
  healthcheckTimeout: 300

[environment]
NODE_ENV = "production"
  restartPolicyType: "ON_FAILURE"

env:
  NODE_ENV: "production"
  PORT: "$PORT"