version: "2"

build:
  builder: "nixpacks"
  buildCommand: "npm install && npm run build"

deploy:
  startCommand: "node start.js"
  healthcheckPath: "/api/health"
  healthcheckTimeout: 300
  restartPolicyType: "ON_FAILURE"

env:
  NODE_ENV: "production"
  PORT: "$PORT"