services:
  - type: web
    name: merlin-bess-quote-builder
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - merlin-bess-quote-builder.onrender.com