export default function handler(req, res) {
  try {
    const { clientName, projectName, power, duration } = req.query;
    
    // Create CSV content (Excel-compatible)
    const csvContent = `"BESS Quote Breakdown"
"Client","${clientName || 'TBD'}"
"Project","${projectName || 'Untitled'}"
"Date","${new Date().toLocaleDateString()}"
"Power","${power || 'TBD'}"
"Duration","${duration || 'TBD'}"

"Component","Base Cost","Notes"
"Battery System","$2,500,000","150 $/kWh baseline"
"Power Conversion","$550,000","110 $/kW baseline"  
"Balance of System","$382,500","15% of equipment"
"EPC & Installation","$858,750","25% project margin"
"Total System Cost","$4,291,250","Complete turnkey solution"

"Generated by Merlin BESS Quote Builder"
"Date: ${new Date().toISOString()}"`;

    const filename = `BESS-Quote-${projectName?.replace(/[^a-zA-Z0-9]/g, '-') || 'Draft'}-${Date.now()}.csv`;
    
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Cache-Control', 'no-cache');
    
    res.status(200).send(csvContent);
    
  } catch (error) {
    console.error('Excel export error:', error);
    res.status(500).json({ error: 'Export failed', details: error.message });
  }
}
