export default function handler(req, res) {
  const { clientName, projectName, power, duration, gridMode, useCase } = req.query;
  
  const wordContent = `BESS Quote - ${projectName || 'Untitled'}

Client: ${clientName || 'TBD'}
Power: ${power || 'TBD'}
Duration: ${duration || 'TBD'} hours
Grid Mode: ${gridMode || 'TBD'}
Application: ${useCase || 'TBD'}

Generated by Merlin BESS Quote Builder
Date: ${new Date().toLocaleDateString()}`;

  res.setHeader('Content-Type', 'application/octet-stream');
  res.setHeader('Content-Disposition', `attachment; filename="BESS-Quote-${projectName || 'Draft'}.txt"`);
  
  res.status(200).send(wordContent);
}
